version: '3.8'
services:
  scylla:
    image: scylladb/scylla:latest
    container_name: scylla
    volumes:
      - scylla-data:/var/lib/scylla
    environment:
      SCYLLA_AUTO_CONF: 1
      SCYLLA_ENABLE_EXPERIMENTAL: 1
  proxy:
    image: linera-test
    container_name: proxy
    ports:
      - "19100:19100"
    command: [ "./compose-proxy-entrypoint.sh" ]
    volumes:
      - .:/config
      - shared:/shared
  shard:
    image: linera-test
    container_name: shard
    command: [ "./compose-server-entrypoint.sh" ]
    volumes:
      - .:/config
      - shared:/shared
    depends_on:
      - shard-init
  shard-init:
    image: linera-test
    container_name: shard-init
    command: [ "./compose-server-init.sh" ]
    volumes:
      - .:/config
      - shared:/shared
    depends_on:
      - scylla

volumes:
  scylla-data:
    driver: local
  shared: # used for cross-container comms.
