version: '3.8'
services:
  scylla:
    image: scylladb/scylla:latest
    container_name: scylla
    volumes:
      - linera-scylla-data:/var/lib/scylla
    environment:
      SCYLLA_AUTO_CONF: 1
    command:
      - "--developer-mode"
      - "0"
      - "--overprovisioned"
      - "1"
  proxy:
    image: linera
    container_name: proxy
    ports:
      - "19100:19100"
    command: [ "./compose-proxy-entrypoint.sh" ]
    volumes:
      - .:/config
      - linera-shared:/shared
  shard:
    image: linera
    container_name: shard
    command: [ "./compose-server-entrypoint.sh" ]
    volumes:
      - .:/config
      - linera-shared:/shared
    depends_on:
      - shard-init
  shard-init:
    image: linera
    container_name: shard-init
    command: [ "./compose-server-init.sh" ]
    volumes:
      - .:/config
      - linera-shared:/shared
    depends_on:
      - scylla

volumes:
  linera-scylla-data:
    driver: local
  linera-shared: # used for cross-container comms.
