apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/app-protocols: '{"linera-port":"HTTP2"}'
  name: proxy
  labels:
    app: proxy
spec:
  ports:
    - port: 443
      name: linera-port
      targetPort: {{ .Values.proxyPort }}
  selector:
    app: proxy
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      serviceAccountName: linera-admin
      terminationGracePeriodSeconds: 10
      containers:
        - name: linera-proxy
          imagePullPolicy: {{ .Values.lineraImagePullPolicy }}
          image: {{ .Values.lineraImage }}
          ports:
            - containerPort: {{ .Values.proxyPort }}
              name: linera-port
          readinessProbe:
            grpc:
              port: {{ .Values.proxyPort }}
          livenessProbe:
            grpc:
              port: {{ .Values.proxyPort }}
          command: ["./linera-proxy"]
          args: ["server_1.json"]
          env:
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
