# The service exposing the proxy to clients.
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/app-protocols: '{"linera-port":"HTTP2"}'
  name: proxy
  labels:
    app: proxy
spec:
  ports:
    - port: {{ .Values.proxyPort }}
      name: linera-port
      targetPort: {{ .Values.proxyPort }}
  selector:
    app: proxy
  type: NodePort

---

# The service exposing the proxy to shards.
apiVersion: v1
kind: Service
metadata:
  name: proxy-internal
  labels:
    app: proxy-internal
spec:
  ports:
    - port: 20100
      name: linera-port-int
      targetPort: 20100
  selector:
    app: proxy
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      serviceAccountName: linera-admin
      terminationGracePeriodSeconds: 10
      containers:
        - name: linera-proxy
          imagePullPolicy: {{ .Values.lineraImagePullPolicy }}
          image: {{ .Values.lineraImage }}
          ports:
            - containerPort: {{ .Values.proxyPort }}
              name: linera-port
            - containerPort: 20100
              name: linera-port-int
          command: ["./linera-proxy"]
          args: ["/config/server.json"]
          env:
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: validator-config
            items:
              - key: serverConfig
                path: server.json
