apiVersion: v1
kind: Service
metadata:
  name: scylladb
  labels:
    app: scylladb
spec:
  ports:
    - port: 9042
      name: cql
  clusterIP: None
  selector:
    app: scylladb

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scylladb
spec:
  serviceName: "scylladb"
  replicas: 1
  selector:
    matchLabels:
      app: scylladb
  template:
    metadata:
      labels:
        app: scylladb
    spec:
      containers:
        - name: scylladb
          image: scylladb/scylla:5.2
          ports:
            - containerPort: 9042
              name: cql
          volumeMounts:
            - name: scylladb-data
              mountPath: /var/lib/scylla
      volumes:
        - name: scylladb-config
          emptyDir: {}

  volumeClaimTemplates:
    - metadata:
        name: scylladb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi
