apiVersion: v1
kind: Service
metadata:
  name: shards
  labels:
    app: shards
spec:
  ports:
    - port: 19100
      name: http
    - port: 21100
      name: metrics
  clusterIP: None
  selector:
    app: shards
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shards
spec:
  serviceName: "shards"
  replicas: 10
  selector:
    matchLabels:
      app: shards
  template:
    metadata:
      labels:
        app: shards
    spec:
      serviceAccountName: linera-admin
      terminationGracePeriodSeconds: 10
      containers:
        - name: linera-server
          image: {{ .Values.lineraImage }}
          imagePullPolicy: {{ .Values.lineraImagePullPolicy }}
          command: ["./server-entrypoint.sh"]
          env:
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      initContainers:
        - name: linera-server-initializer
          image: {{ .Values.lineraImage }}
          imagePullPolicy: {{ .Values.lineraImagePullPolicy }}
          command: ["./server-init.sh"]
          env:
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
            - name: RUST_BACKTRACE
              value: "1"
