[workspace]
resolver = "2"
members = [
        "counter",
        "crowd-funding",
        "fungible",
        "meta-counter",
        "crowd-funding",
        "reentrant-counter",
        "social",
]

[profile.release]
debug = true
lto = true
opt-level = 'z'
strip = 'debuginfo'

[profile.bench]
debug = true
