[package]
name = "fungible"
version = "0.1.0"
authors = ["Linera <contact@linera.io>"]
edition = "2021"

[dependencies]
async-graphql = { version = "5.0.6", default-features = false }
async-trait = "0.1.52"
bcs = "0.1.3"
linera-sdk = { path = "../../linera-sdk" }
linera-views = { path = "../../linera-views" }
thiserror = "1.0.31"
serde_json = "1.0.93"
serde = { version = "1.0.160", features = ["derive"] }

[[bin]]
name = "fungible_contract"
path = "src/contract.rs"

[[bin]]
name = "fungible_service"
path = "src/service.rs"
