developerMode: true
datacenter: validator
racks:
  - name: rack-1
    members: 1
    storage:
      capacity: 1Gi
    resources:
      limits:
        cpu: 1
        memory: 0.2Gi
      requests:
        cpu: 1
        memory: 0.2Gi
