# Values for charts linera-validator for the dev validator on GCP.

# Linera
lineraImage: us-docker.pkg.dev/linera-io-dev/linera-docker-repo/linera-test-local:latest
lineraImagePullPolicy: Always
logLevel: "debug"
proxyPort: 443

# Loki
loki-stack:
  loki:
    enabled: true
    persistence:
      enabled: true
      size: 10Gi
  grafana:
    enabled: true
    sidecar:
      datasources:
        enabled: true
  promtail:
    enabled: true
    config:
      clients:
        - url: http://linera-core-loki:3100/loki/api/v1/push

# Environment
environment: "GCP"

# GCP
staticIpGcpName: "dev-validator-1"
