[package]
name = "{project_name}"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.52"
bcs = "0.1.3"
futures = "0.3.17"
{linera_sdk_dep}
serde = {{ version = "1.0.130", features = ["derive"] }}
serde_json = "1.0.93"
thiserror = "1.0.31"

[dev-dependencies]
{linera_sdk_dev_dep}
webassembly-test = "0.1.0"

[[bin]]
name = "{project_name}_contract"
path = "src/contract.rs"

[[bin]]
name = "{project_name}_service"
path = "src/service.rs"